# Generated by Django 3.1 on 2020-08-20 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mz_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mz_title', models.CharField(max_length=200)),
                ('mz_text', models.TextField()),
                ('mz_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mz_published_date', models.DateTimeField(blank=True, null=True)),
                ('mz_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
